{% set name = "semchunk" %}
{% set version = "2.2.2" %}
{% set python_min = "3.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/semchunk-{{ version }}.tar.gz
  sha256: 940e89896e64eeb01de97ba60f51c8c7b96c6a3951dfcf574f25ce2146752f52

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - tqdm
    - mpire
    - multiprocess >=0.70.15

test:
  imports:
    - semchunk
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: A fast and lightweight Python library for splitting text into semantically meaningful chunks.
  home: https://github.com/umarbutler/semchunk
  license: MIT
  license_file: LICENCE

extra:
  recipe-maintainers:
    - umarbutler
    - dominictarro
